"""Execution limits for the ReAct loop."""

MAX_REACT_TOOL_ROUNDS = 2
MAX_NO_TOOL_RETRIES = 2
REACT_RECURSION_LIMIT = MAX_REACT_TOOL_ROUNDS * 3 + MAX_NO_TOOL_RETRIES * 2 + 3
POST_TOOL_SCREEN_SETTLE_SECONDS = 0.8
